### PR TITLE
Fixed r_smartpicmip cvar and added a description.

### PR DESCRIPTION
**Pull request by Bucky21659**
-Restricted range on r_smartpicmip to 16 (matching r_picmip).
-Changed r_gammaShaders default to 1 and added a description.
-Custom r_lodscale values now save to cfg.
-Changed default ui_selectedModelIndex value to select Kyle.
-Added new default models.
-Changed team size callvote to only show up on JAPro servers.
-Added clientlist from OpenJK to jaPRO cgame.

### CODE REVIEW

**Comment by kudrys** [comment]
@Bucky21659 Seems like non of both commands r_picmip and r_smartpicmip affects player model textures. It basicly stays the same all the time (top quality). Any idea how to fix it?

**Comment by taysta** [comment]
> @Bucky21659 Seems like non of both commands r_picmip and r_smartpicmip affects player model textures. It basicly stays the same all the time (top quality). Any idea how to fix it?

Try `/styleplayer 12` (in-game)

**Comment by kudrys** [comment]
@taysta  Seems like non of both commands r_picmip and r_smartpicmip affects player model textures. It basicly stays the same all the time (top quality). Any idea how to fix it?
> 
> Try `/styleplayer 12` (in-game)

@taysta Seems like it worked for model, but saber texture still stays the same, it used to be super simple, square like, in vanilla jk. Any ideas? I will try to find ss with what I mean :)

**Comment by kudrys** [comment]
I have found something like this in release 1.4.8:
"Fixed jan/default skin, added nopicmip to all light saber blade textures."

May it be the cause? @Bucky21659 @taysta

**Comment by kudrys** [comment]
I have found screen with settings I want to achive: How to get saber textures like this? 
image

**Comment by taysta** [comment]
Hi I'll look into this over the week for you

**Comment by Bucky21659** [comment]
Yep that was the cause, if you really want the low quality blades then
remove the saber shader from the japro assets pk3

**Comment by kudrys** [comment]
@Bucky21659 @taysta It didnt work, I have removed all 3 shaders, saber, sbrgb and jaPro, Still no effect on saber.

**Comment by kudrys** [comment]
Any other thouths? :)

**Comment by deprale** [comment]
> Any other thouths? :)

noone cares about your unemployed behaviour ... why are you trying to make jedi academy which was released... oh I don't know, 2003 (let that sink in) look worse than god damn dark forces 2 which was released ermmm in 1997?

may we know what in the heck are you doing with your life? go and actually play the game, no one has time for this behaviour, hop on base right now so I can show you what ACTUALLY PLAYING THE GAME does to a bum ass trying to taint my game's GFX superior repertoire -> IP is 74 91 120 154 port is 27016, I'll wait for you there, if I'm not there @ me. 

necroing a 6 year old pull request with this beggar behaviour... please stop.

**Comment by Bucky21659** [comment]
> @Bucky21659 @taysta It didnt work, I have removed all 3 shaders, saber, sbrgb and jaPro, Still no effect on saber.

no clue, if you deleted the sabers.shader from the japro assets pk3 & you still aren't getting the desired results with r_smartpicmip 0 then you must have some other mod conflicting

**Pull request merged**
